server:
  port: 9090

spring:
  application:
    name: munusync-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/munusync
    username: postgres
    password: munusync
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
