server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/munusync
    username: munusync
    password: "munusync"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
